services:
  docmost:
    # https://hub.docker.com/r/docmost/docmost/tags
    image: docmost/docmost:${DOCMOST_TAG}
    depends_on:
      - db
      - redis
    environment:
      APP_URL: "http://localhost:3000"
      APP_SECRET: "${APP_SECRET}"
      DATABASE_URL: "postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}?schema=public"
      REDIS_URL: "redis://redis:6379"
      MAIL_DRIVER: "smtp"
      SMTP_HOST: "${SMTP_HOST}"
      SMTP_PORT: "${SMTP_PORT}"
      SMTP_USERNAME: "${SMTP_USERNAME}"
      SMTP_PASSWORD: "${SMTP_PASSWORD}"
      MAIL_FROM_ADDRESS: "${MAIL_FROM_ADDRESS}"
      MAIL_FROM_NAME: "${MAIL_FROM_NAME}"
      SMTP_SECURE: "false"
    ports:
      - "3000:3000"
    restart: unless-stopped
    volumes:
      - docmost:/app/data/storage

  db:
    # https://hub.docker.com/_/postgres/tags
    image: postgres:${POSTGRES_TAG}
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    restart: unless-stopped
    volumes:
      - db_data:/var/lib/postgresql/data

  redis:
    # https://hub.docker.com/_/postgres/tags
    image: redis:${REDIS_TAG}
    restart: unless-stopped
    volumes:
      - redis_data:/data

  mail:
    # https://hub.docker.com/r/axllent/mailpit/tags
    image: axllent/mailpit:${MAILPIT_TAG}
    ports:
      - "19925:${SMTP_PORT}"
      - "19980:${WEB_PORT}"
    volumes:
      - mail-store:/data
    environment:
      TZ: Asia/Tokyo
      MP_MAX_MESSAGES: 5000
      MP_DATABASE: /data/mailpit.db
      MP_SMTP_AUTH_ACCEPT_ANY: 1
      MP_SMTP_AUTH_ALLOW_INSECURE: 1

volumes:
  docmost:
  db_data:
  redis_data:
  mail-store:
